# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4b55483fbaa55fe067779d3cd210d1663f641c959c8e4d1899c857e163d254df45f946d892bbc6890d61d71a133ed5588ef833873a4ae16422a332dd8eddd1e7

test:
  secret_key_base: 050a05e40de7c705775344c2f9a63e85ad79f68c43382ddd5a743f680c88825ace800ba4de6f64c9ff05c93582e34a7b9fc4055d7618057b3ce976767ee26ddb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
